version: '3.8'
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-app-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Mounts the entire local folder into the container
      - /app/node_modules # Excludes node_modules from mounting (to use container modules)
    environment:
      - NODE_ENV=development
      # Enables file polling for stable Hot Module Replacement (HMR) in Docker on Windows/macOS
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # Necessary for interactive Webpack Dev Server
    tty: true
